#pragma once

#include "stm32f7.h"

#define IRQINDEX(irq)   ((irq) >> 5)
#define IRQBIT(irq)     (1UL << ((irq) & 0x1FUL))
#define IRQPRINDEX(irq) ((irq) >> 2)
#define IRQPRSHIFT(irq) ((irq & 0x3UL) << 3)
#define IRQPRMASK(irq)  (0xFFUL << IRQPRSHIFT(irq))

typedef volatile struct {
  uint32_t ISER[8];
  uint32_t _RESERVED0[24];
  uint32_t ICER[8];
  uint32_t ISPR[8];
  uint32_t _RESERVED1[24];
  uint32_t ICPR[8];
  uint32_t IABR[8];
  uint32_t _RESERVED2[32];
  uint32_t IPR[60];
  uint32_t _RESERVED3[644];
  uint32_t STIR; /* offset 0xF00 */
} nvic_reg_t;

typedef enum {
  NVIC_IRQ_WWDG,
  NVIC_IRQ_PVD,
  NVIC_IRQ_TAMPSTAMP,
  NVIC_IRQ_RTCWAKE,
  NVIC_IRQ_FLASH,
  NVIC_IRQ_RCC,
  NVIC_IRQ_EXTI0,
  NVIC_IRQ_EXTI1,
  NVIC_IRQ_EXTI2,
  NVIC_IRQ_EXTI3,
  NVIC_IRQ_EXTI4,
  NVIC_IRQ_DMA1S0,
  NVIC_IRQ_DMA1S1,
  NVIC_IRQ_DMA1S2,
  NVIC_IRQ_DMA1S3,
  NVIC_IRQ_DMA1S4,
  NVIC_IRQ_DMA1S5,
  NVIC_IRQ_DMA1S6,
  NVIC_IRQ_ADC,
  NVIC_IRQ_CAN1TX,
  NVIC_IRQ_CAN1RX0,
  NVIC_IRQ_CAN1RX1,
  NVIC_IRQ_CAN1SCE,
  NVIC_IRQ_EXTI95,
  NVIC_IRQ_TIM1BRK_TIM9,
  NVIC_IRQ_TIM1UP_TIM10,
  NVIC_IRQ_TIM1TRGCOM_TIM11,
  NVIC_IRQ_TIM1CC,
  NVIC_IRQ_TIM2,
  NVIC_IRQ_TIM3,
  NVIC_IRQ_TIM4,
  NVIC_IRQ_I2C1EV,
  NVIC_IRQ_I2C1ER,
  NVIC_IRQ_I2C2EV,
  NVIC_IRQ_I2C2ER,
  NVIC_IRQ_SPI1,
  NVIC_IRQ_SPI2,
  NVIC_IRQ_USART1,
  NVIC_IRQ_USART2,
  NVIC_IRQ_USART3,
  NVIC_IRQ_EXTI15_10,
  NVIC_IRQ_RTCALARM,
  NVIC_IRQ_OTGFSWAKE,
  NVIC_IRQ_TIM8BRK_TIM12,
  NVIC_IRQ_TIM8UP_TIM13,
  NVIC_IRQ_TIM8TRGCOM_TIM14,
  NVIC_IRQ_TIM8CC,
  NVIC_IRQ_DMA1S7,
  NVIC_IRQ_FSMC,
  NVIC_IRQ_SDMMC1,
  NVIC_IRQ_TIM5,
  NVIC_IRQ_SPI3,
  NVIC_IRQ_UART4,
  NVIC_IRQ_UART5,
  NVIC_IRQ_TIM6_DAC,
  NVIC_IRQ_TIM7,
  NVIC_IRQ_DMA2S0,
  NVIC_IRQ_DMA2S1,
  NVIC_IRQ_DMA2S2,
  NVIC_IRQ_DMA2S3,
  NVIC_IRQ_DMA2S4,
  NVIC_IRQ_ETH,
  NVIC_IRQ_ETHWAKE,
  NVIC_IRQ_CAN2TX,
  NVIC_IRQ_CAN2RX0,
  NVIC_IRQ_CAN2RX1,
  NVIC_IRQ_CAN2SCE,
  NVIC_IRQ_OTGFS,
  NVIC_IRQ_DMA2S5,
  NVIC_IRQ_DMA2S6,
  NVIC_IRQ_DMA2S7,
  NVIC_IRQ_USART6,
  NVIC_IRQ_I2C3EV,
  NVIC_IRQ_I2C3ER,
  NVIC_IRQ_OTGHSEP1OUT,
  NVIC_IRQ_OTGHSEP1IN,
  NVIC_IRQ_OTGHSWAKE,
  NVIC_IRQ_OTGHS,
  NVIC_IRQ_DCMI,
  NVIC_IRQ_CRYP,
  NVIC_IRQ_HASHRNG,
  NVIC_IRQ_FPU,
  NVIC_IRQ_UART7,
  NVIC_IRQ_UART8,
  NVIC_IRQ_SPI4,
  NVIC_IRQ_SPI5,
  NVIC_IRQ_SPI6,
  NVIC_IRQ_SAI1,
  NVIC_IRQ_LCDTFT,
  NVIC_IRQ_LCDTFTERR,
  NVIC_IRQ_DMA2D,
  NVIC_IRQ_SAI2,
  NVIC_IRQ_QUADSPI,
  NVIC_IRQ_LPTIMER1,
  NVIC_IRQ_HDMICEC,
  NVIC_IRQ_I2C4EV,
  NVIC_IRQ_I2C4ER,
  NVIC_IRQ_SPDIFRX,
} nvic_irq_t;

#define NVIC ((nvic_reg_t *)NVIC_BASE)

void nvic_enable_irq(nvic_irq_t irq);
void nvic_disable_irq(nvic_irq_t irq);
void nvic_set_priority(nvic_irq_t irq, uint8_t priority);
